# Introdução

## Hunt & Lautzenheiser

### Uma definição de capitalismo

Hunt e Lautzenheiser [@hunt2011] consideram em sua abordagem metodológica que o _modo de produção_ define o sistema econômico. Por sua vez, o modo de produção é definido por 2 componentes: _as forças produtivas_ e as _relações sociais de produção_. 

As _forças produtivas_ também são chamadas de tecnologia produtiva da sociedade. O que inclui: conhecimento técnológico (incluindo conhecimento organizacional), ferramentas, máquinas e prédios usados na produção. Um modo de produção deve prover as formas de sustentação dos custos de manutenção do sistema, incluindo a extração de materia prima, a substituição de equipamentos desgastados, e a sustentação dos seres-humanos envolvidos com o processo produtivo. Nos casos onde um modo de produção não satisfaça estas necessidades, eles desaparecem.

Os modos de produção que persistem são aqueles que além de produzirem o suficiente para atender às necessidades mínimas, também produzem um _excedente social_.
O _excedente social_ é a parte da produção que sobre após serem deduzidos os custos materiais necessários para a produção.

A perspectiva histórica mostra que as forças produtivas têm conseguido gerar excedentes produtivos cada vez maiores. Também na perspectiva histórica percebe-se nas sociedades que envolvem as forças produtivas a divisão da mesma em dois grupos. Uma maioria da população que trabalha para sustentar e perpetuar o modo de produção. E uma minoria que se apropria do excedente social e o controla. A este arranjo de classes sociais chamamos _relações sociais de produção_.

Através destas definições podemos definir o capitalismo como um _modo de produção_ com quatro arranjos institucionais:
1. produção de mercadorias orientada para o mercado;
2. propriedade privada dos meios de produção;
3. um grande segmento da população que não pode existir a não ser que venda sua força de trabalho no mercado;
4. e um comportamento individualista, aquisitivo, maximizador da maioria dos indivíduos.

Também no capitalismos temos a definição de valor em duas perspectivas distintas. A primeira, chamada de _valor de uso_ cuja origem está no fato dos produtos possuirem características físicas que o tornam utilizáveis e satisfazem às necessidades humanas. A segunda, chamada de _valor de troca_ está relacionado ao fato do produto poder ser trocado por dinheiro, o qual pode ser utilizado para troca por outros produtos que possuem valor de uso desejado. Na medida em que os produtos tem valor, porque podem ser trocados por moedas, dizemos que possuem _valor de troca_.

Vamos analisar cada uma das 4 características do capitalismo:

**1. Produção de mercadorias orientada para o mercado**

Para existir _valor de troca_ é preciso que o modo de produção seja caracterizado pela _produção de mercadorias_, que se caracteriza pela existência de um mercado desenvolvido onde os produtos possam ser livremente comprados e vendidos em troca de moeda, e que a produção seja voltada para o _valor de troca_ e não para uso ou consumo pessoal imediato. Nesta situação a atividade produtiva de uma pessoa não possui nenhuma relação direta com seu consumo. A atividade produtiva é direcionada ao mercado e à troca. Assim como não há relação das pessoas com as outras pessoas que produzem as mercadorias que consomem. Esta relação é também mediada pelo mercado.

<span style="color: purple;">
A forma como os autores apresentam esta questão tem uma conotação negativa, como se a existência do mercado ou a produção de mercadorias fosse algo negativo.        
Dentro de uma perspectiva contemporâne me parece um absurdo qualquer situação diferente desta. Não faz sentido eu ser proprietário de uma criação de ovelhas e de uma tecelagem para poder ter uma blusa de lã.        
Neste sentido o mercado é uma entidade libertadora. 
Também a afirmação da falta de relação entre as pessoas que produzem e as pessoas que consomem, parece cercada de um tom negativo. Mas isto é de fato algo muito bom.      
A despersonificação que o mercado traz para o processo de troca ajuda a eliminar favorecimentos e preconceitos. De outra forma, sem esta despersonificação alguém poderia ser privado de uma mercadoria simplesmente pelo fato do produtor não concordar com as posições religiosas, políticas da pessoa compradora, ou até mesmo por simples desavença.
</span>


**2. propriedade privada dos meios de produção**

A organização da sociedade dá a certas pessoas o direito de decidir como matérias primas, ferramentas, prédios e outros instrumentos destinados à produção devam ser utilizados. O que implica automaticamente no fato de que outro grupo de pessoas será excluído deste processo decisório.

O proprietário não precisa possuir qualquer papel direto no processo produtivo para precisar controlá-lo. A 

<span style="color: purple;">
Mais uma vez os autores apresentam o conceito cercado de uma visão negativa.     
A propriedade privada como uma força repressora do possuidor sobre os que não são possuidores.     
A propriedade privada implica em capacidade de tomar decisões sobre seu uso que gerem benefícios pessoais. No caso de más decisões sobre o uso da propriedade privada, há o risco de perda da mesma por ineficiência de sua gestão. 
Isto significa que a propriedade privada é acompanhada de uma responsabilidade pelo seu uso.    
O importante aqui é garantir uma _relação social_ que evite a manutenção da propriedade privada por força que não seja da geração de benefício para o conjunto do mercado. Claro que isto implica em toda uma discussão do que seja benefício para o conjunto. Mas de outro lado, a discussão é muito mais simples se percebemos que na história há bons indícios de que "o mercado" é muito cruel com a má gestão da propriedade privada.
</span>


**3. um grande segmento da população que não pode existir a não ser que venda sua força de trabalho no mercado**

No capitalismo, a maioria dos trabalhadores não possui as matérias primas nem os implementos com os quais produz mercadorias. Isto quer dizer que os trabalhadores não possuem nem os insumos, nem as ferramentas, nem as mercadorias resultantes do processo produtivo. Todos estes pertencem ao proprietário do meio de produção. 

Desta forma, um trabalhador entra no mercado possuindo e controlando apenas sua força de trabalho. E, para se dedicar à atividade produtiva precisa vender esta força de trabalho a um proprietário dos meios de produção. Em troca da força de trabalho, recebe um salário. Desta forma, a força de trabalho em si é transformada em mercadoria.


**4. e um comportamento individualista, aquisitivo, maximizador da maioria dos indivíduos**

Para o sistema funcionar é preciso que os trabalhadores produzam mercadorias cujo valor exceda o valor das mercadorias que consomem.

Isto pode ser conseguido diminuindo os salários pagos aos trabalhadores. Com a evolução do sistema os trabalhadores passaram a se organizar em sindicatos para lutar por melhores salários e condições de trabalho.

Outra característica do comportamento individual é a de produção de motivação para o trabalho, como por exemplo o consumismo, caracterizado pela crença de que mais renda significa mais felicidade.        
         
### A economia européia pré-capitalista       

Na Europa pré-capitalista uma grande maioria da produção visava diretamente o sustento individual: alimentação e vestuário.

As relações sociais e produtivas se davam pela tradição medieval organizada nas classes de nobres e servos. Nas cidades as guildas cumpriam o papel de organização da produção, mas também de costumes.

O mais importante avanço tecnológico da Idade Média foi a substituição do sistema de plantio de dois campos para o de três campos. Os ganhos produtivos impactaram no crescimento da população que quase dobrou entre o ano de 1000 e 1300. Que por sua vez impactou no crescimento da população urbana.

### O crescimento do comércio de longa distância

O crescimento do comércio foi sustentado pela evolução econômica interna da Europa Medieval.

Há uma coincidência entre o desenvolvimento do comércio de longa distância com a dissolução do feudalismo na Europa Ocidental. Porém, esta relação não é necessariamente causal já que o mesmo desenvolvimento do comércio coincidiu com um fortalecimento do feudalismo na Europa Oriental. Isto se deve ao fato das diferentes regiões estarem em momentos diferentes de desenvolvimento.

O fator inicial da dissolução do feudalismo na Europa Ocidental se deve principalmente ao fato de existir um _excedente social_ cada vez menor para sustentar uma classe dominante em crescimento.

As cruzadas tiveram papel importante neste processo sendo força para uma expansão comercial. O crescimento da França ocupa um papel importante neste processo.

De outro lado o aumento do comércio resultou no surgimento de centros urbanos de com vocação comercial, que também resultou em produções voltadas exclusivamente para o comércio.

### O sistema doméstico de trabalho e o surgimento da indústria capitalista

O processo de susbstituição indo do artesão na sua oficina, passando pelo capitalista fornecendo a materia prima e contratando o artesão e terminando com o capitalista dono dos insumos, das ferramentas e do prédio onde os artesão trabalhavam a troco de um salário se consolidou até o final do século XVI.     
@hunt2011 discute se surgimento do capitalismo pode ser caracterizado pela existência deste processo, ou se ele já existia antes com as relações comerciais. Os autores apontam que o comércio já existia na Europa feudal. 

<span style="color:purple">
A impressão é de que existe uma relação entre o crescimento do processo comercial e o modo de produção capitalista, onde o primeiro permite o acúmulo de capital para a existência do segundo. Mas os autores não deixam isso claro.
</span>

### O declínio do sistema senhorial

O declínio do sistema senhorial foi necessário para permitir que as relações de trabalho capitalistas pudessem se sobrepor aos arranjos feudais baseados na relação senhorial entre nobres e servos.
Este processo ocorre durante um longo período passando pelos séculos XIII indo até o século XIV quando o sistema senhorial já estava quase eliminado.

### O surgimento da classe trabalhadora

Nos séculos XV e XVI o movimento do cercamento atingiu seu ápice. Este era caracterizado pela eliminação das áreas de uso comum nos feudos, que passaram a ser utilizadas exclusivamente para a produção de ovelhas e lãs. Este processo resultou na diminuição dos laços feudais e no surgimento de uma força de trabalho sem terra, nem meios de produção. 

### Outras forças na transição para o capitalismo

Dentre as principais forças de transição para o capitalismo no século XVI se destacam:
- o crescimento no volume do comércio;
- o sistema industrial de produção doméstica;
- o movimento dos cercamentos;
- a grande inflação de preços.


## Brue

### Introdução e Visão Geral

- Platão (427 - 347 a.C)
Escreveu sobre os benefícios da especialização humana dentro da cidade estado ideal.

- Aristóteles (384 - 322 a.C.)
Artes naturais e não naturais de arquisição.
Aquisição natural inclui caça, pesca e cultivo. Produção de bens para atividades básicas da vida.
Aquisição não-natural envolve a aquisição de bens além da necessidade.

- São Thomás de Aquino (1225 - 1274)
Preço justo: um preço onde nem o comprador nem o vendedor levam vantagem.

Antes de 1500:
- Pouco comércio
- Produção para consumo na comunidade
- Ausência de dinheiro e crédito
- Ausência de estados nacionais soberanos

### Linha do tempo das idéias econômicas

Destacar as relações de influência e aceitação de idéias entre as escolas.

### As cinco perguntas principais

**1. Qual era o cenário histórico da escola?**

É preciso entender como as pessoas pensavam e agiam na época.

**2. Quais os principais dogmas da escola?**

Isto ajuda no entendimento geral do pensamento da escola. Porém é preciso sempre estar atento que as generalizações podem omitir posições e contribuições individuais importantes. Assim, enquanto as generalizações são boas para a aprendizagem, devem ser tratadas com parcimônia.

**3. Quem a escola beneficiou ou procurou beneficiar?**

Para ser popular um sistema de idéias deve se ajustar às necessidade da sociedade ou de parte dela, que o defanda e amplie.

Os indivíduos são guiados por forças de mecado, sociais, políticas e éticas para cooperar entre si. Assim, grupos que compartilham idéias e interesses surgem defendendo um ponto de vista específico.


**4. Como a escola foi válida, ou útil, ou correta na sua época?**

A questão temporal e circunstancial das idéias e pensamentos deve ser considerado para evitar a aplicação fora de contexto ou época de idéias desenvolvidas em ambientes específicos.

**5. Quais dogmas da escola tornaram-se contribuições duradoras?**

Quais contribuições ou idéias passaram no teste do tempo?

## Questões

**1. Qual o raciocínio do autor para excluir a discussão das contribuições ao pensamento econômico antes de 1500?**

O autor elenca algumas contribuições icônicas antes de 1500 como as idéias propostas por Platão, Aristóteles e São Tomás de Aquino. E elenca algumas características do período anterior a 1500 como: a ausência de comércio, a produção para consumo direto, ausência de dinheiro e crédito e ausência de estados soberanos como características do modos econômico pré 1500.

As contribuições pós 1500 sendo elas desenvolvidas sobre realidades que envolvem características diferentes, geraram modelos com conceitos mais próximos ao que entendemos por _modo de produção_, _forças produtivas_ e _arranjos socias da produção_. Estes conceitos podem e devem inclusive serem utilizado para a análise de modelos econômicos pré 1500. 
Porém, fica ao leitor a interpretação de que as características pré 1500, acabaram por gerar modelos econômicos com maior viés moral e não tão valiosos para serem aplicados nos dias atuais. Não obstantes são úteis para entendimento do ambiente destas épocas anteriores.

**2. Explique o significado das setas brancas e pretas que ligam as escolas de pensamento econômico na linha do tempo. Como os precursores de uma escola se distinguem no diagrama dos membros reais de uma escola? Especule por que é difícil, algumas vezes, colocar um economista específico em determinada escola do pensamento econômico.**

As setas brancas indicam relações onde o grupo da escola posterior foi recepitivo às idéias do grupo precursor. Uma seta preta indica que o grupo posterior teve idéias contrárias ao grupo anterior.
No diagrama os nomes dos precursores aparecem acima das caixas, enquanto os nomes dos membros da escola aparecem dentro das caixas.
Em alguns casos - como por exemplo o das linhas tracejadas - percebemos que há bub-grupos de uma determinada escola que são a favor das idéias dos precursores, enquanto há outros sub-grupos que são contra as idéias dos precursores. Da mesma forma as contribuições dos economistas individualmente podem se enquadrar parcialmente nas características de uma escola, e também é possível que um mesmo economista possa variar de posição e idéias conforme o período temporal de sua contribução.

**3. Liste cinco principais perguntas utilizadas neste livro para organizar a discussão de escolas do pensamento econômico. Explique brevemente por que cada pergunta é importante para o entendimento e avaliação de cada escola.**

As cinco perguntas propostas no livro para organizar a discussão de escolas do pensamento econômico são:
1. Qual o cenário histórico da escola?
A perspectiva histórica é importante para entendermos como as pessoas pensavam e agiam na época.
2. Quais os principais dogmas da escola?
Esta perspectiva ajuda de forma didática a entender genéricamente as principais propostas de cada escola. Porém, conforme alertado no livro é preciso tomar cuidado com generalizações no estudo individual das contribuições de cada economista.
3. Quem a escola beneficiou ou procurou beneficiar?
Para as idéias de uma escola serem aceitas e proliferarem é preciso atender às necessidades da sociedade ou de parte dela.
4. Como a escola foi útil, válida ou correta na sua época?
A contextualização da contribuição da escola à sua época é importante para evitarmos avaliar a contribuição da escola fora de contexto.
5. Quais dogmas da escola tornaram-se contribuições duradoras?
Por fim, é preciso avaliar quais idéias surgidas na escola passaram no teste do tempo e persistiram em momentos posteriores.

4. Discussões atuais sobre modelos econômicos.

Twitter sobre artigo de Prichett e Lewis
https://twitter.com/FComim/status/1540435153570467847

No artigo há referência a Robert Lucas. Segue link com biografia dele:
http://www.souzaaranhamachado.com.br/2006/11/grandes-economistas-robert-lucas/

No artigo há referência para o trabalho do J-PAL (Abdul Latif Jameel Poverty Action Lab):
https://www.povertyactionlab.org/


